### ISSUE TITLE
Integrate a static-site generator with a templating engine

### ISSUE THREAD

**Issue by brob** [web-workers/webworkers#5]
Preferably a JS-based site generator.

**Comment by keithmattix** [comment]
[Wintersmith] (http://wintersmith.io/) sees like a good choice.

**Comment by brob** [comment]
I've used Wintersmith on my personal site. If we go in that direction, I'd prefer to avoid the Jade templating engine. Not a fan of its syntax. Would prefer Twig or something similar.

**Comment by keithmattix** [comment]
Would you be ok with haml or nunjucks? There doesn't seem to be a twig
plugin.

**Comment by brob** [comment]
I think nunjucks is the closest to twig it gets for Wintersmith. I'd be down with that. haml earns the same ire from me as Jade with its syntax :smile_cat:

**Comment by ericterpstra** [comment]
omg you guys, JS templates are sooo 2013.  Components. Components are the cats pajamas these days.  I just started playing around with [Gatsby](https://github.com/gatsbyjs/gatsby) - a site generator utilizing Webpack and React.  I'll let you know how it goes. If it doesn't go well, then yeah, metalsmith+nunjucks looks OK.

**Comment by ericterpstra** [comment]
Yeah, never mind. Tried all morning to just get sass working in Gatsby and had no luck.   Wintersmith sounds just fine.

**Comment by keithmattix** [comment]
This didn't work? https://github.com/gatsbyjs/gatsby/releases/tag/v0.7.1

**Comment by ericterpstra** [comment]
negative.  Tried the webpack config in that release. All it did was break things.  Posted an issue here if you're curious: https://github.com/gatsbyjs/gatsby/issues/114

**Comment by KyleAMathews** [comment]
Gatsby has Sass support out-of-the-box now.
